[build]
command = "ng build --configuration production"
publish = "dist/artmap"
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[functions]
directory = "api/functions"
[[plugins]]
package = "@xata.io/netlify"
