[build]
publish = "dist/artmap/browser"
# [context.production]
# command = "npm run prerender"
# [context.deploy-preview]
# command = "npm run prerender:stage"

# [dev]
# command = "npm run dev:ssr"
# publish = "dist/artmap/browser"
[context.production]
command = "ng build --configuration production"
[context.deploy-preview]
command = "ng build --configuration stage"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


[functions]
directory = "api/functions"

[[plugins]]
package = "@xata.io/netlify"
