[build]
publish = "dist/artmap/browser"
[context.production]
command = "npm run prerender"
[context.deploy-preview]
command = "npm run prerender:stage"

# [dev]
# command = "npm run dev:ssr"
# publish = "dist/artmap/browser"
# framework = "#custom"
# autoLaunch = true
# targetPort = 4200
[[redirects]]
  from = "/pin/*"
  to = "/pin/*/index.html"
  status = 200
[[redirects]]
  from = "/map/*"
  to = "/map/index.html"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
directory = "api/functions"

[[plugins]]
package = "@xata.io/netlify"

[[plugins]]
package = "@netlify/plugin-emails"

