[build]
publish = "dist/artmap/browser"
[context.production]
command = "npm run prerender"
[context.deploy-preview]
command = "npm run prerender:stage"

[dev]
command = "npm run dev:ssr"
publish = "dist/artmap/browser"


[functions]
directory = "api/functions"

[[plugins]]
package = "@xata.io/netlify"
