[build]
publish = "dist/artmap/browser"
[context.production]
command = "npm run prerender"
[context.deploy-preview]
command = "npm run prerender:stage"



[functions]
directory = "api/functions"

[[plugins]]
package = "@xata.io/netlify"

[[plugins]]
package = "@netlify/plugin-emails"

