// Generated by Xata Codegen 0.26.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "points",
    columns: [
      { name: "latitude", type: "float" },
      { name: "longitude", type: "float" },
      { name: "cover", type: "file" },
      { name: "title", type: "string", unique: true },
      { name: "description", type: "text" },
      { name: "address", type: "json" },
      { name: "location_description", type: "text" },
      { name: "publisher", type: "link", link: { table: "users" } },
    ],
    revLinks: [
      { column: "point", table: "art_forms_points" },
      { column: "point", table: "flags" },
    ],
  },
  {
    name: "art_forms",
    columns: [{ name: "name", type: "string", unique: true }],
    revLinks: [{ column: "form", table: "art_forms_points" }],
  },
  {
    name: "art_forms_points",
    columns: [
      { name: "point", type: "link", link: { table: "points" } },
      { name: "form", type: "link", link: { table: "art_forms" } },
    ],
  },
  {
    name: "users",
    columns: [],
    revLinks: [
      { column: "publisher", table: "points" },
      { column: "flagged_by", table: "flags" },
    ],
  },
  {
    name: "flags",
    columns: [
      { name: "point", type: "link", link: { table: "points" } },
      { name: "flagged_by", type: "link", link: { table: "users" } },
      { name: "issue", type: "string", notNull: true, defaultValue: "other" },
      {
        name: "description",
        type: "text",
        notNull: true,
        defaultValue: "unspecified",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Points = InferredTypes["points"];
export type PointsRecord = Points & XataRecord;

export type ArtForms = InferredTypes["art_forms"];
export type ArtFormsRecord = ArtForms & XataRecord;

export type ArtFormsPoints = InferredTypes["art_forms_points"];
export type ArtFormsPointsRecord = ArtFormsPoints & XataRecord;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type Flags = InferredTypes["flags"];
export type FlagsRecord = Flags & XataRecord;

export type DatabaseSchema = {
  points: PointsRecord;
  art_forms: ArtFormsRecord;
  art_forms_points: ArtFormsPointsRecord;
  users: UsersRecord;
  flags: FlagsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://a-nvlkv-s-workspace-shskjs.eu-west-1.xata.sh/db/twopack-gallery",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
